version: "3"

services:
  app:
    build: .
    volumes:
      - .:/go/src
  db:
    image: postgres:14.1-alpine
    restart: always
    tty: true
    volumes:
      - .pgdate:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=codepix
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - "9000:80"
    depends_on:
      - db
